# Generated by Django 5.1.4 on 2024-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userlibraryaccount_library_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibraryaccount',
            name='library_card_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
