# Generated by Django 5.1.4 on 2024-12-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userlibraryaccount_library_card_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='depositmodel',
            name='timestamp',
        ),
    ]
